@startuml

skinparam class {
  backgroundColor whitesmoke
  arrowColor dimgrey
  borderColor dimgrey
}

' Abstract Factory Patter
' Factory -> MeasurementNetwork

class Client
note right of Client
This is i.e. pyaerocom
initiated by a config
end note

interface MeasurementsReaderNetwork {
  + list_timeseries_readers() : dict[name, TimerseriesReader]
  + open_timeseries_reader(name, args): TimeseriesReader
  --
  + createProfileReader(): ProfileReader
}

class EBASNetwork <XOR> {
  + open_timeseries_reader(args): TimeseriesReader
  --
  + createProfileReader(): ProfileReader
}

class EEANetwork <XOR> {
  + open_timeseries_reader(args): TimeseriesReader
  --
  + createProfileReader(): ProfileReader
}

interface TimeseriesReader {
  + open_reader(args)
  --
  + open_parameters(): ...
  + get_data(): TimeseriesData
  + stations(): dict[str, TimseriesStation]
  + description(): str,
  + url(): str_to_docs
}

class EBASTimeseriesReader {
  + open_reader(args)
  --
  + get_data(): TimeseriesData
  ...
}

class EEATimeseriesReader {
  + open_reader(args)
  --
  + public get_data(): TimeseriesData
  ...
}

interface ProfileReader {
  getData(): Data
}

class EBASProfileReader {
  +   getData(): Data
}

class EEAProfileReader {
  +   getData(): Data
}

MeasurementsReaderNetwork <|.. EBASNetwork
MeasurementsReaderNetwork <|.. EEANetwork

TimeseriesReader <|.. EBASTimeseriesReader
TimeseriesReader <|.. EEATimeseriesReader

ProfileReader <|.. EBASProfileReader
ProfileReader <|.. EEAProfileReader


EEANetwork ..> EEAProfileReader
EEANetwork ..> EEATimeseriesReader

EBASNetwork ..> EBASProfileReader
EBASNetwork ..> EBASTimeseriesReader

Client ..> MeasurementsReaderNetwork: imports
Client ..> TimeseriesReader : imports
Client ..> ProfileReader : imports


@enduml
